language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cq-component' ]; then cd .. && eval "mv $currentfolder generator-cq-component" && cd generator-cq-component; fi

